language: python
python:
  - 2.6
  - 2.7
install:
  - python setup.py install
  - pip install -r requirements.txt --use-mirrors
script:
  - mkdir test
  - cd test
  - hazel init
  - hazel write test-post
  - hazel generate
